### PR TITLE
Least portals

### PR DESCRIPTION
**Pull request by NeKzor**
**Changes**
- Fixed `getLeastPortalsBoard` function
- Added route for json data
- Added records for non-public maps
- Updated latest records
- Added buttons in navigation
- Moved `Wall of Shame` button

**Caveats**
Clicking on the YouTube button opens a new tab with a search query. I guess it was planned to show a specific video but this allows users to have more control on what they want to watch.

### CODE REVIEW

**Comment by iVerb1** [comment]
Nice! The reason why I removed the LP boards was because I was not a big fan of two things:

- The Youtube link always seems kind of pointless. I would prefer to have a link directly to a specific video showing off the LP route, since for the most part, everyone uses the same route on every map, and it would be nice to have a single place where all videos are gathered.

- A lack of tracking LP records per player. It could be cool to have a list of people holding the world record per chamber, and an overview on everyone's profile with the LP records that player owns.

I know the second one is a tall order, but I think the first should be doable without too much effort: just store a specific YT link per chamber.

Thoughts?

**Comment by NeKzor** [comment]
The idea behind the current link is that it does not favourite specific channels but I guess
the one who got the record first deserves the attention. Although there are alternative routes that can be very helpful for players. Tracking LP records of everyone is the best idea so people can showcase their own video if they want (I would save that for v2).

Another idea is that we allow submissions only for LP records instead of tracking them. When I wrote the [current LP leaderboard](https://nekzor.github.io/lp) I noticed that there are a lot of less known but also known players who cheated their score (probably using the give command). Some LPs are really difficult to get and submissions can be used as proof here.

**Comment by NeKzor** [comment]
After a lot of research I gathered all video links and added them to the database dump. Chambers without any videos which refer to an LP record will link the SourceRuns video instead.

**Comment by NeKzor** [comment]
Closing this as future leaderboards are better suited for this.

**Pull request closed without merging**
